# about numpy

## 0. dimention

In [20]:
import numpy as np

v1 = np.array(0)
print(v1.shape, type(v1.shape))

v1 = np.array([0])
print(v1.shape, type(v1.shape))

() <class 'tuple'>
(1,) <class 'tuple'>


## 1. index view and copy

In [1]:
import numpy as np

########## slice index ###########
v1 = [1, 2, 3, 4, 5]
print(v1[3:9])

v2 = v1[:2]
v2[:] = [0, 0]
print(v1)

x = np.arange(5)
print('x:', x)

tmp = x[0]
tmp = 99
print('x:', x)

tmp = x[:2]         # view
tmp[:] = 83
print('x:', x)

########## array index ##########
tmp = x[[0,1]]      # copy
print(tmp)
tmp[:] = 73
print(x)

tmp = x[np.array([0,1])]     # copy
print(tmp)
tmp[:] = 73
print(x)

x = np.ones((3, 3))
print(x)
tmp = x[np.array([0]), :]    # copy
tmp[:] = 73
print(x)

tmp = x[np.array([0, 1]), :] # copy
print(tmp)
tmp[0] = 73
print(tmp)
print(x)

tmp = x[:1, :]               # view
print(tmp)
tmp[0] = 73
print(x)

[4, 5]
[1, 2, 3, 4, 5]
x: [0 1 2 3 4]
x: [0 1 2 3 4]
x: [83 83  2  3  4]
[83 83]
[83 83  2  3  4]
[83 83]
[83 83  2  3  4]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[73. 73. 73.]
 [ 1.  1.  1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]]
[[73. 73. 73.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


# numpy TEST

In [1]:
import numpy as np
from itertools import combinations
import time

In [16]:
# v1 = np.array([1, 0, 0, 1, 2, 3, 5, 0, 0])
# v1 = np.where(v1 != 0)
# print(v1)

# v2 = np.array([[0, 1, 2, 3],
#                [4, 5, 6, 7]])
# v2 = v2.reshape((-1,2,2))
# print(v2)

# v3 = np.array([[[0, 1]],
#                [[2, 7]],
#                [[-1, 0]],
#                [[8, -8]]])
# print(v3.shape)
# print(v3.max(axis=0))
v4 = np.array([0, 1, 2, 3, 4])
print(np.expand_dims(v4, axis=0))
print(v4[:,np.newaxis])

v4 = np.array([[1, 0, 3]])
v5 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
v5 = np.square(v5 - v4)
print(v5)
print(np.sum(v5, axis=-1))
print(np.argsort(np.sum(v5, axis=-1)))

print('******* np.argpartition ******')
v1 = np.array([3, 4, 2, 1])
v2 = np.argpartition(v1, 2)
print(v1[v2])
v1 = np.array([9, 8, 2, 0, 2, 1, 3, 4])
v2 = np.argpartition(v1, -4)[-4:]
print(v1[v2])
v2 = np.argpartition(v1, -4)
print(v1[v2])

print('******* itertools ******')
v1 = combinations(range(250), 2)
print(list(v1)[:3], 'v1 len:', len(list(v1)), 250 * 249 // 2)

print('******* np.where ******')
v1 = np.array([1, 2, 3, 6, 7, 3, 0])
v2 = np.where(v1 < 3)
print(v2)
v1 = np.array([[[1, 2, 4, 6], [0, 2, 4, 7]]])
v2 = np.where(v1 < 3)
print(v2)

print('******* slice ******')
v1 = np.array([[1, 2, 3, 4],
               [2, 3, 4, 5],
               [3, 4, 5, 6],
               [4, 5, 6, 7]])
print(v1[[0,1,2],[1,2,3]])
print(v1[[0,1,2],[1]])

print('******* np.linalg.norm ******')
x = np.array([[1, 2, 3, 4],
              [1, 2, 3, 4]])
print(np.sqrt(30.0))
x_norm=np.linalg.norm(x, ord=None, axis=1, keepdims=True)
print(x_norm)

print('******* sort ******')
x = np.array([[4], [1], [2], [5]])
x_idx = np.argsort(x, axis=0)
print(x_idx)
print(x[x_idx.flatten()])

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  4  0]
 [ 9 25  9]
 [36 64 36]]
[  4  43 136]
[0 1 2]
******* np.argpartition ******
[1 2 3 4]
[3 4 8 9]
[0 1 2 2 3 4 8 9]
******* itertools ******
[(0, 1), (0, 2), (0, 3)] v1 len: 0 31125
******* np.where ******
(array([0, 1, 6]),)
(array([0, 0, 0, 0]), array([0, 0, 1, 1]), array([0, 1, 0, 1]))
******* slice ******
[2 4 6]
[2 3 4]
******* np.linalg.norm ******
5.477225575051661
[[5.47722558]
 [5.47722558]]
******* sort ******
[[1]
 [2]
 [0]
 [3]]
[[1]
 [2]
 [4]
 [5]]


# about torch

In [3]:
import torch
import torch.nn.functional as F

In [8]:
v1 = torch.randn(3, 2)
v2 = F.log_softmax(v1, dim=-1)
print(v2)
print(v1)
print(v1.sum(1, keepdim=True))

tensor([[-1.3326, -0.3062],
        [-0.0907, -2.4451],
        [-0.5685, -0.8356]])
tensor([[-1.5459, -0.5194],
        [ 1.8468, -0.5077],
        [ 0.9614,  0.6943]])
tensor([[-2.0653],
        [ 1.3391],
        [ 1.6557]])


In [10]:
v1 = torch.FloatTensor([0.1, 1.9, 3.7, 2.4])
v2 = torch.FloatTensor([3, 0, 2, 5])
v3 = v1 > v2
print(v3.to(torch.float32))
print(v3.dtype)
print(v3, v2[v3])
# print(v3.to(torch.float32))

v4 = torch.BoolTensor([True, False, True])
v5 = torch.BoolTensor([False, False, False])
print(v4 > v5)

tensor([0., 1., 1., 0.])
torch.bool
tensor([False,  True,  True, False]) tensor([0., 2.])
tensor([ True, False,  True])


# Image Operator

In [ ]:
from PIL import Image
import numpy as np
from matplotlib import pyplot as plt

img_path = '/Users/muzhi/Downloads/tmp/1.jpg'
den_path = '/Users/muzhi/Downloads/tmp/1.csv'

img = Image.open(img_path)
if img.mode == 'L':
    img.convert('RGB')
w, h = img.size

img_ny = np.asarray(img)
shape = img_ny.shape  # (h, w, c)
dtype = img_ny.dtype  # (np.uint8)
d_max, d_min = np.max(img_ny), np.min(img_ny)
print(shape, dtype, d_max, d_min)

# np.uint8 image to float
img_ny = img_ny / 255.0
print(img_ny.max(), img_ny.min())

# fromarray must be uint8
im = Image.fromarray(img_ny.astype('uint8'))
print(im.mode)
new_im = np.asarray(im)
print(new_im.shape, new_im.dtype, new_im.max(), new_im.min())

p_img = plt.imread(img_path)
print(p_img.shape, p_img.dtype)

lst = [{'a': [123]}, {'a': [456, 123]},{'b': [789, 456]}]

dic = {}
for _ in lst:
    for k, v in _.items():
        dic.setdefault(k, []).extend(v)

print(dic)