In [2]:
import numpy as np
import torch
import torchvision

# numpy TEST

In [12]:
# v1 = np.array([1, 0, 0, 1, 2, 3, 5, 0, 0])
# v1 = np.where(v1 != 0)
# print(v1)

# v2 = np.array([[0, 1, 2, 3],
#                [4, 5, 6, 7]])
# v2 = v2.reshape((-1,2,2))
# print(v2)

# v3 = np.array([[[0, 1]],
#                [[2, 7]],
#                [[-1, 0]],
#                [[8, -8]]])
# print(v3.shape)
# print(v3.max(axis=0))
v4 = np.array([0, 1, 2, 3, 4])
print(np.expand_dims(v4, axis=0))
print(v4[:,np.newaxis])

v4 = np.array([[1, 0, 3]])
v5 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
v5 = np.square(v5 - v4)
print(v5)
print(np.sum(v5, axis=-1))
print(np.argsort(np.sum(v5, axis=-1)))

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  4  0]
 [ 9 25  9]
 [36 64 36]]
[  4  43 136]
[0 1 2]


# about torch

### 1. DataLoader

In [13]:
import torch.utils.data as data
from torch.utils.data.sampler import Sampler

In [25]:
class MyDataset(data.Dataset):
    def __init__(self):
        self.data = torch.eye(7)
        self.data_len = self.data.size(0)
        
    def __getitem__(self, index):
        print(index)
        return self.data[index]
    
    def __len__(self):
        return int(self.data_len)
    
class Samp(Sampler):
    def __init__(self):
        self.smp = np.array([0, 1, 4, 6, 3, 2, 5])
        self.smp_len = len(self.smp)
    
    def __iter__(self):
        return iter(self.smp)
    
    def __len__(self):
        return self.smp_len


mydataset = MyDataset()    
samp = Samp()

dataloader = data.DataLoader(mydataset,
                             batch_size=3,
                             shuffle=False,
                             sampler=samp)

for i, v in enumerate(dataloader):
    print(v)

0
1
4
tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.]])
6
3
2
tensor([[0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.]])
5
tensor([[0., 0., 0., 0., 0., 1., 0.]])


### 2. Tensor

In [11]:
t1 = torch.randn(3, 3)
print(t1.size(0), type(t1.size(0)))

3 <class 'int'>


### 3. some func api

In [3]:
s1 = torch.randn(3, 3)
s2 = torch.max(s1, 1)
print(s1)
print(s2)

s3 = torch.randn(7, 5, 4)
print(s3)
s4 = torch.max(s3, 2)
print(s4)
s5 = torch.max(s3, 1)
print(s5)

tensor([[ 0.9422,  2.2302, -0.6731],
        [ 0.1782,  1.0912, -0.5894],
        [ 0.5980,  0.5205, -0.3998]])
torch.return_types.max(
values=tensor([2.2302, 1.0912, 0.5980]),
indices=tensor([1, 1, 0]))
tensor([[[-1.2189,  0.3860,  0.6612, -0.5503],
         [ 0.0235,  1.4213,  0.8730,  0.1270],
         [ 1.7497, -0.7082, -1.4129,  0.4653],
         [-0.8298,  0.3792, -1.8405,  0.1535],
         [ 0.2550, -1.4524, -0.5629,  1.0850]],

        [[-1.8875,  0.9664,  0.8628, -0.9391],
         [-1.7569,  1.2431,  0.1463, -0.4209],
         [-1.3757, -0.4443, -1.6345,  1.6738],
         [-0.1588, -1.8369,  0.5406,  0.8178],
         [-0.9371,  0.5605, -0.4585,  0.4215]],

        [[-1.6968, -0.5511,  0.7867,  0.4336],
         [-0.5813, -0.3624, -0.3887,  0.9923],
         [ 0.1936,  0.7338, -0.9608,  0.6367],
         [-0.1973,  0.3087, -1.5334, -1.3575],
         [-0.8923, -0.0491,  0.4147,  0.3574]],

        [[ 0.3110, -0.2247,  0.2613,  1.6110],
         [-1.6648,  1.1230,  0.4536, -

# Only Test Something 

In [18]:
import os
print(os.path.join('.', 'asda/asd.jpg'))

./asda/asd.jpg
