In [4]:
import numpy as np
import torch
import torchvision

# about numpy

In [3]:
v1 = np.array([1, 0, 0, 1, 2, 3, 5, 0, 0])
v1 = np.where(v1 != 0)
print(v1)

(array([0, 3, 4, 5, 6]),)


# about torch

### 1. DataLoader

In [13]:
import torch.utils.data as data
from torch.utils.data.sampler import Sampler

In [25]:
class MyDataset(data.Dataset):
    def __init__(self):
        self.data = torch.eye(7)
        self.data_len = self.data.size(0)
        
    def __getitem__(self, index):
        print(index)
        return self.data[index]
    
    def __len__(self):
        return int(self.data_len)
    
class Samp(Sampler):
    def __init__(self):
        self.smp = np.array([0, 1, 4, 6, 3, 2, 5])
        self.smp_len = len(self.smp)
    
    def __iter__(self):
        return iter(self.smp)
    
    def __len__(self):
        return self.smp_len


mydataset = MyDataset()    
samp = Samp()

dataloader = data.DataLoader(mydataset,
                             batch_size=3,
                             shuffle=False,
                             sampler=samp)

for i, v in enumerate(dataloader):
    print(v)

0
1
4
tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.]])
6
3
2
tensor([[0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.]])
5
tensor([[0., 0., 0., 0., 0., 1., 0.]])


### 2. Tensor

In [11]:
t1 = torch.randn(3, 3)
print(t1.size(0), type(t1.size(0)))

3 <class 'int'>
