In [25]:
import torch

## Only TEST

In [39]:
a = torch.ones(3)
print(a.size)
lg = a.size(0)
torch.arange(lg).dtype

a = torch.ones(3, 2, dtype=torch.float32)
a1 = torch.max(a, 0)
print(a1)

t1 = torch.tensor([0, 1, 0, 1, 0, 0])
t2 = torch.tensor([0, 1, 1, 0, 1, 0])
t3 = t1 & t2
print(t3)

<built-in method size of Tensor object at 0x7f6ca9095288>
torch.return_types.max(
values=tensor([1., 1.]),
indices=tensor([2, 2]))
tensor([0, 1, 0, 0, 0, 0])


## About Tensor

In [23]:
a2 = torch.tensor([[1, 2], [3, 4]], requires_grad=True, dtype=torch.float32)
a3 = a2.data
print(type(a2.data), type(a2))
print(a2.requires_grad, a2.data.requires_grad)

a4 = a3.new(1, 2, 3).zero_()
print(a4, a4.dtype)

print(a4.size(), a4.size(0), type(a4.size(0)))

a5 = torch.FloatTensor([0., 0., 0., 0.])
print(a5, a5.dtype)


# pytorch version tansfer
from torch.autograd import Variable
b1 = torch.randn(3, 2)
print(b1, b1.dtype, b1.requires_grad)
b2 = b1.view(-1).long()
print(b2, b2.dtype, b2.requires_grad)
b3 = Variable(b2)
print(b3, b3.dtype, b3.requires_grad)

print('************')
c1 = torch.randn(2, 3, dtype=torch.float32, requires_grad=False)
c2 = c1.unsqueeze(0)
print(c1)
print(c2 is c1)

<class 'torch.Tensor'> <class 'torch.Tensor'>
True False
tensor([[[0., 0., 0.],
         [0., 0., 0.]]]) torch.float32
torch.Size([1, 2, 3]) 1 <class 'int'>
tensor([0., 0., 0., 0.]) torch.float32
tensor([[ 2.0655,  1.0536],
        [-2.0452,  0.7222],
        [-1.6556,  0.0340]]) torch.float32 False
tensor([ 2,  1, -2,  0, -1,  0]) torch.int64 False
tensor([ 2,  1, -2,  0, -1,  0]) torch.int64 False
************
tensor([[-1.6682,  0.7630,  0.0081],
        [-0.5083,  0.2246, -0.3151]])
False


## example 1

In [17]:
x = torch.ones(2, 3, requires_grad=True)
y = x * x + 2
out = y.mean()
print(x.requires_grad)
print(y, y.requires_grad)
print(out)

True
tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>) True
tensor(3., grad_fn=<MeanBackward0>)


**this is dynamic graph**

when you run a second time bellow cell, will error:

*Trying to backward through the graph a second time, but the buffers have already been freed*

In [27]:
# out.backward()
out.backward(torch.tensor(3.))
print(x.grad)
print(y.grad)  # only x has grad ??

tensor([[1., 1., 1.],
        [1., 1., 1.]])
None


## example 2

In [49]:
x1 = torch.tensor(3.0, requires_grad=True)

In [52]:
# now this cell can run serval times, and x1.grad is accelerated
# if y1 = x1 * x1 + x1 + 3 move up cell, this cell cannot run tow times.
y1 = x1 * x1 + x1 + 3
print(y1)
y1.backward()
print(x1)
print(x1.grad)

tensor(15., grad_fn=<AddBackward0>)
tensor(3., requires_grad=True)
tensor(14.)


## about DOC api

> Otherwise, contiguous() needs to be called before the tensor can be viewed. See also: reshape(), which returns a view if the shapes are compatible, and copies (equivalent to calling contiguous()) otherwise.

In [8]:
import torch
import numpy as np

In [9]:
x3 = torch.ones(10, 10)
print(x3.is_contiguous())  # True
print(x3.transpose(0, 1).is_contiguous())  # False
print(x3.transpose(0, 1).contiguous().is_contiguous())  # True

True
False
True


In [14]:
x4 = torch.from_numpy(np.arange(0, 9))
x4 = x4.view(1, 3, 3)
x5 = torch.ones(2, 1, 3).type_as(x4)
print(x4)
print(x5)
x6 = x4 + x5
print(x6)

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])
tensor([[[1, 1, 1]],

        [[1, 1, 1]]])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


### about slice

In [22]:
a1 = np.arange(1, 5, 0.5)
print(a1, a1.shape)
print(a1[0], a1[0].shape)
print(a1[:2], a1[:2].shape)
print(a1[0::9])

[1.  1.5 2.  2.5 3.  3.5 4.  4.5] (8,)
1.0 ()
[1.  1.5] (2,)
[1.]


### about shape

In [24]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)
torch.unsqueeze(x, 1)

x1 = torch.randn(1, 2, 3, 4)
x2 = x1.view(1, 2, -1, 2)
print(x2.size())

torch.Size([1, 2, 6, 2])


### about sort

In [42]:
x = torch.randn(3, 4)
print(x)
x_sorted, order = torch.sort(x, 1, True)
print(x_sorted)
print(order)

tensor([[ 1.4505, -1.0772, -0.0899, -1.0181],
        [-0.5671, -0.0263, -0.5105, -0.4859],
        [ 0.8140,  0.7063,  0.0172,  0.7241]])
tensor([[ 1.4505, -0.0899, -1.0181, -1.0772],
        [-0.0263, -0.4859, -0.5105, -0.5671],
        [ 0.8140,  0.7241,  0.7063,  0.0172]])
tensor([[0, 2, 3, 1],
        [1, 3, 2, 0],
        [0, 3, 1, 2]])


In [50]:
x = torch.randn(2, 2)
print(x)
print(x<0)
x[x<0] = 1.
print(x)

tensor([[ 0.2046,  0.7479],
        [-0.8057, -1.7067]])
tensor([[0, 0],
        [1, 1]], dtype=torch.uint8)
tensor([[0.2046, 0.7479],
        [1.0000, 1.0000]])
