# numpy TEST

In [15]:
import numpy as np
from itertools import combinations
import time

In [33]:
# v1 = np.array([1, 0, 0, 1, 2, 3, 5, 0, 0])
# v1 = np.where(v1 != 0)
# print(v1)

# v2 = np.array([[0, 1, 2, 3],
#                [4, 5, 6, 7]])
# v2 = v2.reshape((-1,2,2))
# print(v2)

# v3 = np.array([[[0, 1]],
#                [[2, 7]],
#                [[-1, 0]],
#                [[8, -8]]])
# print(v3.shape)
# print(v3.max(axis=0))
v4 = np.array([0, 1, 2, 3, 4])
print(np.expand_dims(v4, axis=0))
print(v4[:,np.newaxis])

v4 = np.array([[1, 0, 3]])
v5 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
v5 = np.square(v5 - v4)
print(v5)
print(np.sum(v5, axis=-1))
print(np.argsort(np.sum(v5, axis=-1)))

print('******* np.argpartition ******')
v1 = np.array([3, 4, 2, 1])
v2 = np.argpartition(v1, 2)
print(v1[v2])
v1 = np.array([9, 8, 2, 0, 2, 1, 3, 4])
v2 = np.argpartition(v1, -4)[-4:]
print(v1[v2])
v2 = np.argpartition(v1, -4)
print(v1[v2])

print('******* itertools ******')
v1 = combinations(range(250), 2)
print(list(v1)[:3], 'v1 len:', len(list(v1)), 250 * 249 // 2)

print('******* np.where ******')
v1 = np.array([1, 2, 3, 6, 7, 3, 0])
v2 = np.where(v1 < 3)
print(v2)
v1 = np.array([[[1, 2, 4, 6], [0, 2, 4, 7]]])
v2 = np.where(v1 < 3)
print(v2)

print('******* slice ******')
v1 = np.array([[1, 2, 3, 4],
               [2, 3, 4, 5],
               [3, 4, 5, 6],
               [4, 5, 6, 7]])
print(v1[[0,1,2],[1,2,3]])
print(v1[[0,1,2],[1]])


[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  4  0]
 [ 9 25  9]
 [36 64 36]]
[  4  43 136]
[0 1 2]
******* np.argpartition ******
[1 2 3 4]
[3 4 8 9]
[0 1 2 2 3 4 8 9]
******* itertools ******
[(0, 1), (0, 2), (0, 3)] v1 len: 0 31125
******* np.where ******
(array([0, 1, 6]),)
(array([0, 0, 0, 0]), array([0, 0, 1, 1]), array([0, 1, 0, 1]))
******* slice ******
[2 4 6]
[2 3 4]


# about torch

In [3]:
import torch
import torch.nn.functional as F

In [8]:
v1 = torch.randn(3, 2)
v2 = F.log_softmax(v1, dim=-1)
print(v2)
print(v1)
print(v1.sum(1, keepdim=True))

tensor([[-1.3326, -0.3062],
        [-0.0907, -2.4451],
        [-0.5685, -0.8356]])
tensor([[-1.5459, -0.5194],
        [ 1.8468, -0.5077],
        [ 0.9614,  0.6943]])
tensor([[-2.0653],
        [ 1.3391],
        [ 1.6557]])
